name: Publish to PyPI

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    download-sources:
        name: Download and store sources
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3

            - name: Download external sources
              run: |
                  make prepare-src
                  make download-sqlite
                  make download-sqlean

            - name: Store sources
              uses: actions/upload-artifact@v3
              with:
                  name: sources
                  path: |
                      MANIFEST.in
                      Makefile
                      setup.cfg
                      setup.py
                      sqlean
                      src
                      sqlite
                      test

    build:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        needs: download-sources
        strategy:
            matrix:
                # os: [ubuntu-latest, windows-latest, macos-latest]
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Download sources
              uses: actions/download-artifact@v3
              with:
                  name: sources

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.13.1
              env:
                  CIBW_SKIP: pp*

            - name: Store wheels
              uses: actions/upload-artifact@v3
              with:
                  name: wheels
                  path: ./wheelhouse/*.whl

    # publish:
    #     name: Publish to PyPI
    #     needs: build
    #     runs-on: ubuntu-latest
    #     permissions:
    #         id-token: write
    #     steps:
    #         - name: Download wheels
    #           uses: actions/download-artifact@v3
    #           with:
    #               name: wheels
    #               path: dist

    #         - name: Publish to PyPI
    #           uses: pypa/gh-action-pypi-publish@release/v1
